In [1]:
import numpy as np


In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]=100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)
slice_arr = arr[0:6]
slice_arr

array([0, 1, 2, 3, 4, 5])

In [12]:
slice_arr[:]=99

In [13]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1,2]

30

In [18]:
arr_2d[1,1]

25

In [22]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [23]:
arr2d = np.zeros((10,10))

In [27]:
arr_length = arr2d.shape[0]
arr_length

10

In [30]:
arr = np.arange(0,11)

In [31]:
arr_bool = arr > 4

In [32]:
arr_bool

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [33]:
arr[arr_bool]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])