In [2]:
my_list=[1,2,3]


In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(1)

array([1.])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [20]:
np.random.rand(2)

array([0.56961326, 0.02423224])

In [22]:
np.random.rand(5,5)

array([[0.66682951, 0.59242166, 0.0276844 , 0.26197565, 0.04792322],
       [0.08615874, 0.5006976 , 0.06356594, 0.84750733, 0.41925077],
       [0.84621578, 0.96719073, 0.53565925, 0.74591179, 0.82818861],
       [0.64225478, 0.4634575 , 0.00477806, 0.33073131, 0.58285244],
       [0.78825343, 0.30016698, 0.15589551, 0.977086  , 0.76693984]])

In [23]:
np.random.randn(2)

array([-0.29438282, -0.16648121])

In [24]:
np.random.rand(3,3)

array([[0.36030336, 0.95089841, 0.14302584],
       [0.8004926 , 0.62745306, 0.80621742],
       [0.12197173, 0.24198474, 0.86801427]])

In [26]:
np.random.randint(2)

1

In [27]:
np.random.randint(1,100,4)

array([53, 93,  9, 10])

In [28]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr.max()

49

In [32]:
ranarr.min()

7

In [34]:
ranarr.argmin()

0

In [35]:
ranarr.argmax()

2

In [36]:
arr.shape

(25,)

In [37]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
arr.reshape(1,25).shape


(1, 25)

In [39]:
arr.dtype

dtype('int32')