In [1]:
import numpy as np

Create 10 5 

In [2]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

Create an array of all the even integers from 10 to 50

In [4]:
arr = np.arange(10,51,2)

In [5]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
np.random.randn(25)

array([ 0.7125724 , -0.32683208,  0.47563256, -1.49905833, -0.41017872,
        0.52698852, -0.58804532, -2.15251246, -0.17234558,  1.4011262 ,
        1.22603191,  0.95240246, -0.80046271,  0.9875139 , -0.50940382,
       -0.50291531,  0.39009028,  1.29836889, -0.61554512,  0.59422915,
        0.27905462, -0.60725668, -0.21193768, -0.66395219, -2.56170539])

In [11]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])